name: bone-fracture-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - streamlit>=1.25.0
      - opencv-python-headless>=4.8.0.74
      - tensorflow>=2.12.0
      - numpy>=1.24.3,<2.0.0
      - pandas>=1.5.3
      - scikit-learn>=1.3.0
      - matplotlib>=3.7.2
      - pillow>=9.5.0
      - joblib>=1.3.2
      - protobuf>=3.20.3
